# 预定义变量
# LIB_NAME
# LIB_VERSIONED_NAME
# LIB_SOURCE_DIR
# LIB_INSTALL_PREFIX

# 构建和安装命令
set(LIB_CMAKE_ARGS
        -DCMAKE_INSTALL_PREFIX=${LIB_INSTALL_PREFIX}
        -DCMAKE_BUILD_TYPE=${BUILD_TYPE}
        -DBUILD_SHARED_LIBS=ON
        # 随cpptrace一起编译
        -DCPPTRACE_ZSTD_SOURCE_DIR=${SRC_DIR}/${NAME_ZSTD}-${VERSION_ZSTD}
        -DCPPTRACE_DWARF_SOURCE_DIR=${SRC_DIR}/${NAME_DWARF}-${VERSION_DWARF}
)

set(LIB_BUILD_COMMAND
        make -j16
)
set(LIB_INSTALL_COMMAND
        make install
)

# 依赖
set(LIB_DEPENDS "")

ExternalProject_Add(
        ${LIB_NAME}
        SOURCE_DIR ${LIB_SOURCE_DIR}
        BINARY_DIR ${LIB_SOURCE_DIR}/build
        CMAKE_ARGS ${LIB_CMAKE_ARGS}
        BUILD_COMMAND ${LIB_BUILD_COMMAND}
        INSTALL_COMMAND ${LIB_INSTALL_COMMAND}
        LOG_CONFIGURE ON
        LOG_BUILD ON
        LOG_INSTALL ON
        DEPENDS ${LIB_DEPENDS}
)