# 预定义变量
# LIB_NAME
# LIB_VERSIONED_NAME
# LIB_SOURCE_DIR
# LIB_INSTALL_PREFIX

set(PKG_CONFIG_PATH ${INSTALL_DIR}/${NAME_APR}/lib/pkgconfig)

# 构建和安装命令
set(LIB_CMAKE_ARGS
        -DCMAKE_INSTALL_PREFIX=${LIB_INSTALL_PREFIX}
        -DCMAKE_BUILD_TYPE=${BUILD_TYPE}
        -DCMAKE_C_COMPILER=${CMAKE_C_COMPILER}
        -DCMAKE_CXX_COMPILER=${CMAKE_CXX_COMPILER}
        -DBUILD_SHARED_LIBS=ON
        -DBUILD_STATIC_LIBS=OFF
        # 不编译测试代码
        -DBUILD_TESTING=off
)
set(LIB_BUILD_COMMAND make -j16)
set(LIB_INSTALL_COMMAND make install)

# 依赖
set(LIB_DEPENDS
        ${NAME_APR}
        ${NAME_APR_UTIL}
)

ExternalProject_Add(
        ${LIB_NAME}
        SOURCE_DIR ${LIB_SOURCE_DIR}
        BINARY_DIR ${LIB_SOURCE_DIR}/build
        CONFIGURE_COMMAND ${CMAKE_COMMAND}
        # 设置PKG_CONFIG_PATH环境变量
        -E env PKG_CONFIG_PATH=${PKG_CONFIG_PATH}
        # 执行CMake构建
        ${CMAKE_COMMAND} ${LIB_SOURCE_DIR} ${LIB_CMAKE_ARGS}

        BUILD_COMMAND ${LIB_BUILD_COMMAND}
        INSTALL_COMMAND ${LIB_INSTALL_COMMAND}
        BUILD_ALWAYS OFF
        LOG_CONFIGURE ON
        LOG_BUILD ON
        LOG_INSTALL ON
        DEPENDS ${LIB_DEPENDS}
)